server:
   port: 5000
   tomcat:
     max-swallow-size: -1
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://<rds db endpoint>:3306/dbwhippystore
    username: XXXX
    password: XXXX
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: XXXX
            clientSecret: XXXX
            scope: openid
            redirect-uri: http://localhost:5000/login/oauth2/code/cognito
            clientName: XXXX
            
          okta:
            client-id: XXXX
            client-secret: XXXX
            rolesClaim: groups
           
        provider:
          cognito:
            issuerUri: https://cognito-idp.<region>.amazonaws.com/<pool-id>
            user-name-attribute: cognito:username
            
          okta:
            issuer-uri: X
            
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB   
      
 
            
amazonProperties:
  endpointUrl: https://s3.<region>.amazonaws.com
  accessKey: XXXX
  secretKey: XXXX
  bucketName: <bucket-name>
  
  

      
      
      
logout:
  uri: http://localhost:5000/
  
cloudfront:
  uri: <cloudfront-distribution>
